import Head from "next/head";
import Header from "components/Header";
import { useTheme } from "utils/hook/useTheme";
import Calculator from "components/Calculator";
export default function Home() {
  const { theme } = useTheme();
  return (
    <>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Calculator />
      </main>
      <footer>footer</footer>
    </>
  );
}
